"""
Regenerates js/assets.js from the PNGs in assets/.

Only needed if you add or change a bundled image. The app itself has no build
step: it reads the generated file directly.

Why embed at all: a page opened from file:// has an opaque origin, so an image
loaded from another file:// path "taints" any canvas it touches, and uploading
a tainted canvas to WebGL throws a SecurityError. Data URLs are same-origin, so
embedding them is what lets index.html run by double-clicking it.

Usage:  python tools/embed_assets.py
"""
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# key -> display name. Order here is the order in the menus; the first entry of
# each group is the default.
BACKGROUNDS = {
    "lens": "Lens",
    "empty": "Empty",
    "parabola": "Parabola",
    "disks": "Disks",
    "fresnel": "Fresnel Lens",
}
GRADIENTS = {
    "blue-white-red": "Blue White Red",
    "grayscale": "Gray Scale",
    "plasma": "Plasma",
    "viridis": "Viridis",
    "heat": "Heat",
    "magma": "Magma",
}


def group(folder, names):
    out = {}
    for key, name in names.items():
        data = (ROOT / "assets" / folder / f"{key}.png").read_bytes()
        out[key] = {
            "name": name,
            "src": "data:image/png;base64," + base64.b64encode(data).decode("ascii"),
        }
    return out


def main():
    assets = {
        "backgrounds": group("backgrounds", BACKGROUNDS),
        "gradients": group("gradients", GRADIENTS),
    }
    body = json.dumps(assets, indent=1)
    text = (
        "// GENERATED by tools/embed_assets.py - do not edit by hand.\n"
        "// Bundled images as data URLs, so the app works from file:// (see the script).\n"
        "'use strict'\n"
        f"const ASSETS = Object.freeze({body})\n"
    )
    out = ROOT / "js" / "assets.js"
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(text) // 1024} KB)")


if __name__ == "__main__":
    main()
